[pytest]
testpaths = web/tests
norecursedirs = temp .git __pycache__
filterwarnings =
    ignore:Using `httpx` with `starlette.testclient` is deprecated.*:starlette.exceptions.StarletteDeprecationWarning
